import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/Header";
import { SafeAreaLayout } from "./components/SafeAreaLayout";
import { MainAreaLayout } from "./components/MainAreaLayout";
import Welcome from "./Welcome";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-200 dark:bg-neutral-900`}>

          <div className="flex flex-col md:flex-row w-full h-full min-h-full bg-neutral-200 dark:bg-neutral-900 overflow-visible md:overflow-clip ">
      
              <div className="w-screen md:w-1/2 flex flex-col h-full ">
                <Welcome></Welcome>

              </div>
              <div className='w-screen md:w-1/2 flex flex-col h-screen md:overflow-clip'>
                {children}
              </div>

            



          </div>
        

      </body>
    </html>
  );
}
